-- ============================================================
-- Drop old tables if they exist
-- ============================================================
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS ledlum_products CASCADE;

-- ============================================================
-- Create ledlum_products table
-- ============================================================
CREATE TABLE ledlum_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model TEXT NOT NULL UNIQUE,
    family TEXT,
    category TEXT,
    group_name TEXT,
    collection TEXT DEFAULT 'indoor',
    hero_image TEXT,
    hero_description TEXT,
    gallery_images TEXT[] DEFAULT '{}',
    watts TEXT,
    dimensions TEXT,
    cutout_size TEXT,
    body_colors TEXT[] DEFAULT '{}',
    cct TEXT[] DEFAULT '{}',
    beam_angle TEXT,
    ip_rating TEXT,
    led_chip TEXT,
    luminous TEXT,
    cri TEXT,
    website TEXT,
    product_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- Enable Row Level Security (RLS)
-- ============================================================
ALTER TABLE ledlum_products ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Policies
-- ============================================================

-- Anonymous read policy (frontend can fetch)
DROP POLICY IF EXISTS "Allow public read access" ON ledlum_products;
CREATE POLICY "Allow public read access"
ON ledlum_products FOR SELECT
TO anon
USING (true);

-- Service role write policy (import script can upsert)
DROP POLICY IF EXISTS "Allow service role write access" ON ledlum_products;
CREATE POLICY "Allow service role write access"
ON ledlum_products FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- ============================================================
-- Indexes for fast filtering
-- ============================================================
CREATE INDEX idx_ledlum_products_website ON ledlum_products (website);
CREATE INDEX idx_ledlum_products_family ON ledlum_products (family);
CREATE INDEX idx_ledlum_products_category ON ledlum_products (category);
CREATE INDEX idx_ledlum_products_group_name ON ledlum_products (group_name);
CREATE INDEX idx_ledlum_products_model ON ledlum_products (model);

-- ============================================================
-- RPC: returns only products where website = 'W' or 'w'
-- ============================================================
CREATE OR REPLACE FUNCTION get_website_products()
RETURNS SETOF ledlum_products
LANGUAGE sql
STABLE
AS $$
  SELECT *
  FROM ledlum_products
  WHERE upper(website) = 'W'
  ORDER BY model;
$$;

-- ============================================================
-- RPC: reset table + identity sequence
-- ============================================================
CREATE OR REPLACE FUNCTION reset_products_table()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  TRUNCATE TABLE ledlum_products RESTART IDENTITY;
END;
$$;
