-- ============================================================
-- Create body_colors table
-- Canonical name -> hex-code mapping for product body colors,
-- seeded from the excel-derived color names (scripts/seed-body-colors.ts)
-- so the frontend swatches come from the DB instead of a hardcoded map.
-- ============================================================
CREATE TABLE IF NOT EXISTS body_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    hex_code TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- Enable Row Level Security (RLS)
-- ============================================================
ALTER TABLE body_colors ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Policies
-- ============================================================

DROP POLICY IF EXISTS "Allow public read access" ON body_colors;
CREATE POLICY "Allow public read access"
ON body_colors FOR SELECT
TO anon
USING (true);

DROP POLICY IF EXISTS "Allow service role write access" ON body_colors;
CREATE POLICY "Allow service role write access"
ON body_colors FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- ============================================================
-- Index for fast slug lookup
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_body_colors_slug ON body_colors (slug);
