-- ============================================================
-- CMS tables for the /admin panel.
--
-- Every table here is written AND read only through the
-- service_role key on the server (lib/supabaseAdmin.ts), so RLS is
-- enabled with no anon policies — the public anon key can't read
-- admin users, submissions, or unpublished drafts.
-- ============================================================

-- ------------------------------------------------------------
-- Admin users (named logins with roles, replaces the single
-- shared ADMIN_PASSWORD). password_hash is "scrypt$<salt>$<hash>"
-- generated in lib/adminAuth.ts.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'editor' CHECK (role IN ('admin', 'editor')),
    active BOOLEAN NOT NULL DEFAULT true,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service role write access" ON admin_users;
CREATE POLICY "Allow service role write access"
ON admin_users FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- ------------------------------------------------------------
-- Page sections / site settings. One row per editable block,
-- keyed like 'home.hero' or 'site.settings'; data is whatever
-- shape that block's schema in lib/cms/schema.ts defines.
-- Missing rows fall back to the defaults in lib/cms/defaults.ts.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cms_content (
    key TEXT PRIMARY KEY,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_by TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE cms_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service role write access" ON cms_content;
CREATE POLICY "Allow service role write access"
ON cms_content FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- ------------------------------------------------------------
-- Blog posts (replaces lib/blogData.ts — seed with
-- scripts/seed-cms-posts.ts).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cms_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    image TEXT,
    mid_section_title TEXT,
    paragraphs TEXT[] DEFAULT '{}',
    mid_section_image TEXT,
    outcome_sections JSONB DEFAULT '[]'::jsonb,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    is_featured BOOLEAN NOT NULL DEFAULT false,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    seo_title TEXT,
    seo_description TEXT,
    updated_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE cms_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service role write access" ON cms_posts;
CREATE POLICY "Allow service role write access"
ON cms_posts FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_cms_posts_published_date
  ON cms_posts (date DESC)
  WHERE status = 'published';

-- ------------------------------------------------------------
-- Form submissions inbox (contact / quote / catalog lead).
-- Saved alongside the existing Resend emails.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS form_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('contact', 'quote', 'lead')),
    name TEXT,
    email TEXT,
    phone TEXT,
    product TEXT,
    message TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'archived')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE form_submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service role write access" ON form_submissions;
CREATE POLICY "Allow service role write access"
ON form_submissions FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_form_submissions_created
  ON form_submissions (created_at DESC);
